services:
    tsuserver:
        build: .
        image: tsuserver
        network_mode: "host"
        volumes:
            - ./storage:/app/storage
            - ./logs:/app/logs
            - ./config:/app/config
        restart: unless-stopped

